# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://vandenboom.icu/archive/"
DefaultContentLanguage  = "nl"
title                   = "Notities"
theme                   = "hugo-future-imperfect-slim"
paginate                = 6
disqusShortname         = "www-vandenboom-icu"
googleAnalytics         = "G-PX9BKD4YYT"
pluralizeListTitles     = false
disableLanguages        = []

# Build robots.txt file
enableRobotsTXT         = true

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  author                = "van den Boom"
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
  hideEmptyStats        = false

  [params.meta]
    description         = "A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
    author              = "van den Boom"
    favicon             = true
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Notities"
    dynamicTitles       = true
    searchMenu          = false
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "Notities"
    paragraph             = "ing. M.A.C.M. (Martijn) van den Boom </br></br> Computer Infrastructure Architect </br> ingenieur, docent en mentor</br></br>"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "https://vandenboom.netlify.app/images/Martijn_001.jpg"
      shape               = "circle"
      width               = ""
      alt                 = "Notities"

  [params.sidebar]
    about               = "Sponsor me link: </br> <a href='https://ko-fi.com/martijnvandenboom'>ko-fi.com/martijnvandenboom</a> </br> <a href='https://paypal.me/ingmacmvandenboom'>paypal.me/ingmacmvandenboom</a> </br> <a href='https://buymeacoffee.com/ingvdboom'>buymeacoffee.com/ingvdboom</a>"
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = false
    api                 = "api.staticman.net"  # No Trailing Slash
    gitProvider         = "github"
    username            = "martijnvandenboom"
    repo                = "backup-website"
    branch              = "main"

    [params.staticman.recaptcha]
      siteKey           = "6LeYtQYaAAAAAIRQjBkZTA59iEa3OBI3hxWWMFx_"
      encryptedKey      = "6LeYtQYaAAAAAK5CSKSbh_UvF5_ngEi5VS14GYqm"

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/archive/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 4
  
  [[menu.main]]
    name              = "Services"
    identifier        = "services"
    url               = "/services/"
    pre               = "<i class='fas fa-briefcase'></i>"
    weight            = 5


  [[menu.main]]
    name              = "Archive"
    identifier        = "archive"
    url               = "/archive/"
    pre               = "<i class='fas fa-archive'></i>"
    weight            = 6

[Languages]

  [Languages.nl]
    LanguageCode        = "nl"
    LanguageName        = "Nederlands"
    weight              = 10

    [[Languages.nl.menu.main]]
      name              = "Home"
      identifier        = "home"
      url               = "/archive/"
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.nl.menu.main]]
      name              = "Over"
      identifier        = "about"
      url               = "/about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.nl.menu.main]]
      name              = "Blog"
      identifier        = "blog"
      url               = "/blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.nl.menu.main]]
      name              = "Categorieën"
      identifier        = "categories"
      url               = "/categories/"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 4

    [[Languages.nl.menu.main]]
      name              = "Services"
      identifier        = "services"
      url               = "/services/"
      pre               = "<i class='fas fa-briefcase'></i>"
      weight            = 5

    [[Languages.nl.menu.main]]
      name              = "Archief"
      identifier        = "archive"
      url               = "/archive/"
      pre               = "<i class='fas fa-archive'></i>"
      weight            = 6

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

[social]
  # Coding Communities
  github                = "martijnvandenboom"
  #gitlab                = ""
  stackoverflow         = "13417146" # User Number
  bitbucket             = "martijnvandenboom"
  #jsfiddle              = ""
  #codepen               = ""
  docker				 = "martijnvandenboom"
  # Visual Art Communities
  deviantart            = "ingvdboom"
  #flickr                = "example"
  #behance               = ""
  #dribbble              = ""
  # Publishing Communities
  #wordpress             = ""
  #medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "macmvandenboom"
  #linkedin_company      = "examplebusiness"
  #foursquare            = ""
  xing                  = "MACMMartijn_vandenBoom"
  #slideshare            = ""
  # Social Networks
  facebook              = "macmvandenboom"
  #googleplus            = ""
  #reddit                = "example"
  #quora                 = ""
  youtube               = "channel/UCslXipyVBwsTe6UjhVNOz7A"
  vimeo                 = "macmvandenboom"
  #whatsapp              = "" # WhatsApp Number
  # WeChat and QQ need testing.
  #wechat              = ""
  #qq                  = "" # User ID Number
  instagram             = "ingmacmvandenboom"
  #tumblr                = ""
  spotify               = "0d6z61v65xapwjgn7n416pc1j"
  soundcloud            = "ing-macm-van-den-boom"
  lastfm				= "ingvdboom"
  tiktok				= "martijn.vandenboom"
  twitter               = "ingvdboom"
  #strava                = ""
  skype                 = "mvdboom@live.com"
  snapchat              = "ingvdboom"
  pinterest             = "macmvandenboom"
  telegram              = "ingvdboom"
  #vine                  = ""
  #googlescholar         = ""
  #orcid                 = ""
  #researchgate          = "example"
  #keybase               = "example"
  #mastodon              = "example.com/@example"
  # Email
  email                 = "ingmacmvandenboom@gmail.com"
